apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: x7lu3s3ju-nodejs 
  janus-idp.io/tekton: x7lu3s3ju-nodejs
  backstage.io/kubernetes-id: x7lu3s3ju-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: x7lu3s3ju-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml