apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: x7lu3s3ju-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: x7lu3s3ju-nodejs 
  name: x7lu3s3ju-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: x7lu3s3ju-nodejs 
